### ISSUE TITLE
ElementNameImpl.toString() is wrongfully escaping *

### ISSUE THREAD

**Issue by mirraj2** [radkovo/jStyleParser#109]
```css
* {
 color: red;
}
```

becomes

```css
\* {
  color: red
}
```

it should probably just do:

```java
if(WILDCARD.equals(name)){
  return name;
} else{
  return CssEscape.escapeCssIdentifier(name);
}
```
