### ISSUE TITLE
selector with invalid pseudo-class should discard the entire rule

### ISSUE THREAD

**Issue by hrj** [radkovo/jStyleParser#46]
Apropos [this test](https://test.csswg.org/suites/css21_dev/nightly-unstable/xhtml1/selectors-parsing-001.xht):

```css
   p:invalidPseudoClass, p.test1 { color: yellow; background: red; }
```

The whole rule should be discarded, but it doesn't.
