### ISSUE TITLE
reject width and height when they are negative

### ISSUE THREAD

**Issue by hrj** [radkovo/jStyleParser#47]
A few more tests that check for invalid CSS, such as:

```css
div {
    background: red;
    height: 1in;
    width: 0;
    width: -1px;
}
```

Here, the node-data should show a width of 0, instead of `-1px`.

Tests affected:
* xhtml1/width-001.xht
* xhtml1/height-001.xht
