### ISSUE TITLE
URL function with escaped special chars - single quote

### ISSUE THREAD

**Issue by hrj** [radkovo/jStyleParser#48]
> Single quote characters appearing in an unquoted URI need to be escaped with a backslash so that the resulting URI value is a URI token.

Test-case: xhtml1/uri-005.xht

CSS: 

``` css
            p
            {
                color: white;
                background: red url(support/\'green\ block.png);
            }

```

In node data: `background-image: url('support/\'green block.png');`

I am logging this as an issue here because the space character is being escaped correctly. So, escaping the quote character need not be very different, I guess.
