### ISSUE TITLE
font-family:serif doesn't override a font-family property 

### ISSUE THREAD

**Issue by hrj** [radkovo/jStyleParser#50]
CSS:
```css
html { font-family: 'Ahem' }
p { font-family: serif }
```

HTML:
```html
<html>
<p>Test</p>
</html>
```

The `p` element doesn't get `font-family:serif`.
